### ISSUE TITLE
Review for doc `aws-s3.md`

### ISSUE THREAD

**Issue by gaoran10** [streamnative/pulsar-hub#109]
## Some Suggestions About [AWS-S3 Doc](https://github.com/streamnative/pulsar-hub/blob/master/offloaders/aws-s3/2.5.1/aws-s3.md)

1. Prerequisite

This is AWS S3 doc, maybe we could don't care about `Filesystem`.

2. Copy the Pulsar offloaders as offloaders in the Pulsar directory.

We only need the `tiered-storage-jcloud-2.5.1.nar`.

3. Set the environment variables AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY in conf/pulsar_env.s.

The conf file name is `pulsar_env.sh`.

4. modify `ledge` to `ledger`.

> The offloading operation starts after a ledge rollover is triggered. To ensure offload data successfully, it is recommended that you wait until several ledge rollovers are triggered. In this case, you might need to wait for a second. You can check the ledge status using pulsar-admin.

5. Whether we need to add introduce about namespace offload policies in this doc. 

The namespace offload policies is a common config for cloud storage and filesystem storage.

**Comment by Anonymitaet** [comment]
@gaoran10 thanks for your review

#2: I think the original text is not incorrect, the `offloaders` folder includes `tiered-storage-file-system-2.5.1.nar` and `tiered-storage-jcloud-2.5.1.nar`. Copy the `offloaders` folder is correct behavior as well.

#3, #4 thanks for your comments, I'll update

#5: I've already added "namespace policy" related contents in the "Configure AWS S3 offloader to run automatically" section, is it OK?
![image](https://user-images.githubusercontent.com/50226895/83582411-f9dc2e00-a573-11ea-93b5-cc14db7bf866.png)

@wolfstudy What's ur opinions on #1?

**Comment by gaoran10** [comment]
@Anonymitaet 

About suggestion 2, the aws s3 could be used normally, but users introduced a non-required file `tiered-storage-file-system-2.6.0-SNAPSHOT.nar`.

About suggestion 5, each namespace could have its own offload policies. The offload config in `broker.conf` and `standalone.conf` is used for the namespaces that don't have namespace level offload policies.

The command used to set namespace offload policies. refer to [here](http://pulsar.apache.org/tools/pulsar-admin/2.6.0-SNAPSHOT/#-em-set-offload-policies-em-)
```
bin/pulsar-admin namespaces set-offload-policies -b test-pulsar-offload-1 -d aws-s3 -r ap-south-1 -oae 1000 public/default
```

**Comment by wolfstudy** [comment]
About #1, aggre with @gaoran10 

@gaoran10 about #5, Configuring the relevant options in standalone.conf and using pulsar-admin can achieve the same purpose. We can introduce set-offload-policies in the document, but we must explain this, right?

**Comment by Anonymitaet** [comment]
@gaoran10 @wolfstudy thanks for your comments, docs have been updated.
