### ISSUE TITLE
[doc] Update link in the Hub doc content

### ISSUE THREAD

**Issue by Jennifer88huang** [streamnative/pulsar-hub#122]
On [Pulsar Flink connector](https://hub.streamnative.io/data-processing/pulsar-flink/2.4.12) page, scroll down to the bottom, and click the link. It navigates to https://streamnative.io/docs/v1.0.0/process/pulsar-flink-connector/link/

See screenshot below
![image](https://user-images.githubusercontent.com/47805623/99037196-35b4fe00-25be-11eb-85b6-e457e30c3d27.png)

We can use the link without version number, so when users click the link, they will be navigated to the latest one or the latest stable content.

Check if we have similar cases in the whole hub docs.

**Comment by tuteng** [comment]
ping @zeo1995 

```
[[redirects]]
  from = "/docs/v1.0.0/process/pulsar-flink-connector/link/"
  to = "https://docs.streamnative.io/platform/v1.0.0/process/pulsar-flink-connector/overview"
  status = 301
```

/docs/v1.0.0/process/pulsar-flink-connector/link/ => https://docs.streamnative.io/platform/v1.0.0/process/pulsar-flink-connector/overview
