### ISSUE TITLE
Refine the ownership of offloaders

### ISSUE THREAD

**Issue by Jennifer88huang** [streamnative/pulsar-hub#131]
These offloaders belong to ASF. Currently, SN logo is displayed https://hub.streamnative.io/
![image](https://user-images.githubusercontent.com/47805623/104695010-04d08100-5747-11eb-8912-eb254ea44f81.png)

**Comment by Jennifer88huang** [comment]
Reference: https://github.com/streamnative/pulsar-hub/pull/106
https://github.com/streamnative/pulsar-hub/pull/30/files

**Comment by sijia-w** [comment]
#133

**Comment by Jennifer88huang** [comment]
You can write Fixes #131 in the description of PR 133, and when PR 133 is merged, this issue will close automatically.
