### ISSUE TITLE
[website] Add specific category in the hub website

### ISSUE THREAD

**Issue by Jennifer88huang** [streamnative/pulsar-hub#134]
When adding reference to the SN hub, we have different categories, yet all points to the same URL.
Is it possible that we add specific categories after the general link, take the following as reference
![image](https://user-images.githubusercontent.com/47805623/106410761-8aaa3700-647e-11eb-806b-2c14a826aa0d.png)

**Comment by tuteng** [comment]
Fixed https://hub.streamnative.io/connectors/activemq-sink/2.5.1/
