### ISSUE TITLE
Oldest version listed first on StreamNative owned connectors

### ISSUE THREAD

**Issue by alpreu** [streamnative/pulsar-hub#181]
When navigating to [hub.streamnative.io](https://hub.streamnative.io/) and selecting a connector whose doc is synced from a StreamNative repository, the oldest version is listed first.

Steps to reproduce:
1) Go to hub.streamnative.io
2) Select Sinks
3) Select AWS SQS Sink

Outcome: Selected version and document displayed is the oldest (v.2.7.0)
Expected Outcome:  Selected version and document displayed is the newest (v.2.10.x)

**Comment by Huanli-Meng** [comment]
@urfreespace could you please help look into this issue? Thanks.
