### ISSUE TITLE
Add MQTT-on-Pulsar to StreamNative Hub

### ISSUE THREAD

**Issue by sijie** [streamnative/pulsar-hub#97]
Add MQTT-on-Pulsar as a protocol handler in StreamNative Hub.

**Comment by vicaya** [comment]
Thanks guys for working on this! What's the current status and timeline for the mop handler?

**Comment by sijie** [comment]
@vicaya we are planning to release MOP around mid to late July.

**Comment by vicaya** [comment]
Any updates?

**Comment by sijie** [comment]
@vicaya it is coming this week.-

**Comment by Jennifer88huang** [comment]
It's published on https://hub.streamnative.io/protocol-handlers/mop/0.2.0
